### ISSUE TITLE
Создать страничку просматривающую юнитов в gwt и play framework

### ISSUE THREAD

**Issue by cdfeasy** [cdfeasy/Army-Editor#2]

**Comment by cdfeasy** [comment]
юниты это класс com.armyeditor.entrys.unit
база крутится локально, читается локально, пример можно смотреть в fractionEditor
playFramework опционально

**Comment by cdfeasy** [comment]
База заполняется пока вручную

**Comment by AnnaTau** [comment]
вывела один id
