### ISSUE TITLE
Сделать заполнение основных справочников

### ISSUE THREAD

**Issue by cdfeasy** [cdfeasy/Army-Editor#5]
Страничка где можно заполнить 
WeaponBase
OptionBase 
и все остальные Base

**Comment by cdfeasy** [comment]
com.armyeditor.entrys.Armor
com.armyeditor.entrys.AttackType
com.armyeditor.entrys.SpecialRule
com.armyeditor.entrys.UnitType
com.armyeditor.entrys.WeaponType

**Comment by AnnaTau** [comment]
усё
